/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppToolsRouteImport } from './routes/_app/tools'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppJournalRouteImport } from './routes/_app/journal'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppGoalsRouteImport } from './routes/_app/goals'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppActivitiesRouteImport } from './routes/_app/activities'
import { Route as AuthStravaCallbackRouteImport } from './routes/auth.strava.callback'
import { Route as ApiStravaWebhookRouteImport } from './routes/api.strava.webhook'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppToolsRoute = AppToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitiesRoute = AppActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AppRoute,
} as any)
const AuthStravaCallbackRoute = AuthStravaCallbackRouteImport.update({
  id: '/auth/strava/callback',
  path: '/auth/strava/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStravaWebhookRoute = ApiStravaWebhookRouteImport.update({
  id: '/api/strava/webhook',
  path: '/api/strava/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof AppActivitiesRoute
  '/dashboard': typeof AppDashboardRoute
  '/goals': typeof AppGoalsRoute
  '/insights': typeof AppInsightsRoute
  '/journal': typeof AppJournalRoute
  '/profile': typeof AppProfileRoute
  '/tools': typeof AppToolsRoute
  '/api/strava/webhook': typeof ApiStravaWebhookRoute
  '/auth/strava/callback': typeof AuthStravaCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof AppActivitiesRoute
  '/dashboard': typeof AppDashboardRoute
  '/goals': typeof AppGoalsRoute
  '/insights': typeof AppInsightsRoute
  '/journal': typeof AppJournalRoute
  '/profile': typeof AppProfileRoute
  '/tools': typeof AppToolsRoute
  '/api/strava/webhook': typeof ApiStravaWebhookRoute
  '/auth/strava/callback': typeof AuthStravaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/activities': typeof AppActivitiesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/goals': typeof AppGoalsRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/tools': typeof AppToolsRoute
  '/api/strava/webhook': typeof ApiStravaWebhookRoute
  '/auth/strava/callback': typeof AuthStravaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/dashboard'
    | '/goals'
    | '/insights'
    | '/journal'
    | '/profile'
    | '/tools'
    | '/api/strava/webhook'
    | '/auth/strava/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/dashboard'
    | '/goals'
    | '/insights'
    | '/journal'
    | '/profile'
    | '/tools'
    | '/api/strava/webhook'
    | '/auth/strava/callback'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/activities'
    | '/_app/dashboard'
    | '/_app/goals'
    | '/_app/insights'
    | '/_app/journal'
    | '/_app/profile'
    | '/_app/tools'
    | '/api/strava/webhook'
    | '/auth/strava/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiStravaWebhookRoute: typeof ApiStravaWebhookRoute
  AuthStravaCallbackRoute: typeof AuthStravaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tools': {
      id: '/_app/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AppToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals': {
      id: '/_app/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activities': {
      id: '/_app/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AppActivitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/strava/callback': {
      id: '/auth/strava/callback'
      path: '/auth/strava/callback'
      fullPath: '/auth/strava/callback'
      preLoaderRoute: typeof AuthStravaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/strava/webhook': {
      id: '/api/strava/webhook'
      path: '/api/strava/webhook'
      fullPath: '/api/strava/webhook'
      preLoaderRoute: typeof ApiStravaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppActivitiesRoute: typeof AppActivitiesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppJournalRoute: typeof AppJournalRoute
  AppProfileRoute: typeof AppProfileRoute
  AppToolsRoute: typeof AppToolsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivitiesRoute: AppActivitiesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppJournalRoute: AppJournalRoute,
  AppProfileRoute: AppProfileRoute,
  AppToolsRoute: AppToolsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiStravaWebhookRoute: ApiStravaWebhookRoute,
  AuthStravaCallbackRoute: AuthStravaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
