/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppToolsIndexRouteImport } from './routes/_app/tools/index'
import { Route as AppProfileIndexRouteImport } from './routes/_app/profile/index'
import { Route as AppJournalIndexRouteImport } from './routes/_app/journal/index'
import { Route as AppInsightsIndexRouteImport } from './routes/_app/insights/index'
import { Route as AppGoalsIndexRouteImport } from './routes/_app/goals/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppActivitiesIndexRouteImport } from './routes/_app/activities/index'
import { Route as AuthStravaCallbackRouteImport } from './routes/auth.strava.callback'
import { Route as ApiStravaWebhookRouteImport } from './routes/api.strava.webhook'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppToolsIndexRoute = AppToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalIndexRoute = AppJournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsIndexRoute = AppInsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsIndexRoute = AppGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitiesIndexRoute = AppActivitiesIndexRouteImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => AppRoute,
} as any)
const AuthStravaCallbackRoute = AuthStravaCallbackRouteImport.update({
  id: '/auth/strava/callback',
  path: '/auth/strava/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStravaWebhookRoute = ApiStravaWebhookRouteImport.update({
  id: '/api/strava/webhook',
  path: '/api/strava/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/strava/webhook': typeof ApiStravaWebhookRoute
  '/auth/strava/callback': typeof AuthStravaCallbackRoute
  '/activities/': typeof AppActivitiesIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/goals/': typeof AppGoalsIndexRoute
  '/insights/': typeof AppInsightsIndexRoute
  '/journal/': typeof AppJournalIndexRoute
  '/profile/': typeof AppProfileIndexRoute
  '/tools/': typeof AppToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/strava/webhook': typeof ApiStravaWebhookRoute
  '/auth/strava/callback': typeof AuthStravaCallbackRoute
  '/activities': typeof AppActivitiesIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/goals': typeof AppGoalsIndexRoute
  '/insights': typeof AppInsightsIndexRoute
  '/journal': typeof AppJournalIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/tools': typeof AppToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/api/strava/webhook': typeof ApiStravaWebhookRoute
  '/auth/strava/callback': typeof AuthStravaCallbackRoute
  '/_app/activities/': typeof AppActivitiesIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/goals/': typeof AppGoalsIndexRoute
  '/_app/insights/': typeof AppInsightsIndexRoute
  '/_app/journal/': typeof AppJournalIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/tools/': typeof AppToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/strava/webhook'
    | '/auth/strava/callback'
    | '/activities/'
    | '/dashboard/'
    | '/goals/'
    | '/insights/'
    | '/journal/'
    | '/profile/'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/strava/webhook'
    | '/auth/strava/callback'
    | '/activities'
    | '/dashboard'
    | '/goals'
    | '/insights'
    | '/journal'
    | '/profile'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/api/strava/webhook'
    | '/auth/strava/callback'
    | '/_app/activities/'
    | '/_app/dashboard/'
    | '/_app/goals/'
    | '/_app/insights/'
    | '/_app/journal/'
    | '/_app/profile/'
    | '/_app/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiStravaWebhookRoute: typeof ApiStravaWebhookRoute
  AuthStravaCallbackRoute: typeof AuthStravaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tools/': {
      id: '/_app/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof AppToolsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal/': {
      id: '/_app/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof AppJournalIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights/': {
      id: '/_app/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof AppInsightsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals/': {
      id: '/_app/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof AppGoalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activities/': {
      id: '/_app/activities/'
      path: '/activities'
      fullPath: '/activities/'
      preLoaderRoute: typeof AppActivitiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/strava/callback': {
      id: '/auth/strava/callback'
      path: '/auth/strava/callback'
      fullPath: '/auth/strava/callback'
      preLoaderRoute: typeof AuthStravaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/strava/webhook': {
      id: '/api/strava/webhook'
      path: '/api/strava/webhook'
      fullPath: '/api/strava/webhook'
      preLoaderRoute: typeof ApiStravaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppActivitiesIndexRoute: typeof AppActivitiesIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppGoalsIndexRoute: typeof AppGoalsIndexRoute
  AppInsightsIndexRoute: typeof AppInsightsIndexRoute
  AppJournalIndexRoute: typeof AppJournalIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppToolsIndexRoute: typeof AppToolsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivitiesIndexRoute: AppActivitiesIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppGoalsIndexRoute: AppGoalsIndexRoute,
  AppInsightsIndexRoute: AppInsightsIndexRoute,
  AppJournalIndexRoute: AppJournalIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppToolsIndexRoute: AppToolsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiStravaWebhookRoute: ApiStravaWebhookRoute,
  AuthStravaCallbackRoute: AuthStravaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
